from typing import List, Optional
from app.schemas.contracts import Situation, IntakeForm, IntakeField

class IntakeBuilder:
    @staticmethod
    def build(situation: Situation) -> Optional[IntakeForm]:
        if not situation.missing_information:
            return None
            
        fields: List[IntakeField] = []
        missing_lower = [m.lower() for m in situation.missing_information]
        # Ensure jurisdiction is captured if we don't have it, as it's critical for routing
        if not situation.jurisdiction or not situation.jurisdiction.state:
            indian_states_and_uts = [
                "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh",
                "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka",
                "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram",
                "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu",
                "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal",
                "Andaman and Nicobar Islands", "Chandigarh", "Dadra and Nagar Haveli and Daman and Diu",
                "Delhi", "Jammu and Kashmir", "Ladakh", "Lakshadweep", "Puducherry", "Other"
            ]
            fields.append(IntakeField(
                id="jurisdiction",
                label="Which state/UT did this happen in? (Crucial for finding the right laws)",
                type="select",
                options=indian_states_and_uts,
                required=True
            ))
            
        # Add dynamic questions generated by the LLM
        for i, question in enumerate(situation.missing_information[:2]):
            # Use the question string as the ID so it's easy to retrieve context later
            q_id = f"dynamic_q_{i}__{question}"
            fields.append(IntakeField(
                id=q_id,
                label=question,
                type="text",
                required=True,
                placeholder="Your answer..."
            ))
                
        # Always add a free-text fallback if they need to explain more
        fields.append(IntakeField(
            id="additional_facts",
            label="Any other important details?",
            type="text",
            required=False,
            placeholder="Type any additional facts here..."
        ))
        
        return IntakeForm(
            title="We need a few more details to help you correctly",
            fields=fields
        )
